---
title: "`miro`: Visuals for Spatial (Transcript)Omics"
author:
- name: Helena L. Crowell
  affiliation: National Center for Genomics Analysis (CNAG), Barcelona, Spain
output:
  BiocStyle::html_document
abstract: |
  Description of your vignette
vignette: |
  %\VignetteIndexEntry{miro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
date: "`r format(Sys.Date(), '%B %d, %Y')`"
package: "`r BiocStyle::pkg_ver('miro')`"
---

# Preamble

## Introduction

## Dependencies

```{r load-libs, message=FALSE, warning=FALSE}
library(miro)
library(OSTA.data)
library(patchwork)
library(SpatialExperiment)
library(SpatialExperimentIO)
```

```{r load-data, message=FALSE, warning=FALSE}
# retrieve Xenium dataset
id <- "Xenium_HumanColon_Oliveria"
pa <- OSTA.data_load(id)
dir.create(td <- tempfile())
unzip(pa, exdir=td)
(spe <- readXeniumSXE(td))
# crops for demo
xy <- spatialCoords(spe)
spe$roi <- 
    xy[,1]>1000 & xy[,1]<2000 & 
    xy[,2]>1500 & xy[,2]<2500 
spe$roj <- 
    xy[,1]>1400 & xy[,1]<1600 & 
    xy[,2]>1800 & xy[,2]<2000 
p <- "cell_boundaries"
m <- "transcripts"
```

# Centroids

```{r fig.width=4, fig.height=3.5}
miro(spe, dat_aes=list(stroke=0, size=0.2, col="total_counts"), dat_t=log10)
```

# Polygons

```{r fig.height=4, fig.width=4.5}
miro(spe, sub="roi", pol=p, pol_aes=list(fill="cell_area"))
```

# Molecules

```{r fig.height=4, fig.width=4.5}
miro(spe, sub="roi", mol=m, keys=c("DUOX2", "MUC12", "VWF"), mol_aes=list(size=0))
```

# Layering

```{r fig.width=3, fig.height=3}
miro(spe, sub="roj",
    pol=p, pol_aes=list(fill="darkgreen"),
    xy=TRUE, dat_aes=list(col="green", size=0.2))
```

```{r fig.height=4, fig.width=4.5}
miro(spe, sub="roj",
    pol=p, pol_aes=list(fill=NA, col="black", size=0.1),
    mol=m, mol_aes=list(size=0.1), 
    keys=c("DUOX2", "VWF", "MZB1"),
    mol_pal=c("magenta", "blue", "gold"))
```

# Utilities

## subsetting

```{r fig.width=7, fig.height=3.5}
aes <- list(fill="total_counts")
miro(spe, pol=p, sub="roi", pol_aes=aes) +
miro(spe, pol=p, sub="roj", pol_aes=aes) 
```

## highlighting

```{r fig.width=4, fig.height=3.5}
miro(spe, 
    sub="roi", # subset 1st regions
    hl="roj", # highlight 2nd region
    dat_aes=list(col="total_counts", size=0))
```


# Appendix

## Session info {- .smaller}

<style type="text/css">
.smaller {
  font-size: 10px
}
</style>

```{r si, echo=FALSE}
sessionInfo()
```
